# -*- coding: utf-8 -*-
"""AddnT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hL6Bq-2nVwaOVCl1tGjlfFNPR4aEDY7
"""

# AND, NOT and OR gate using perceptron

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

AND_df=pd.DataFrame({'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,0,0,1]})
OR_df=pd.DataFrame({'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,1,1,1]})
NOT_df=pd.DataFrame({'x1':[0,1],'y':[1,0]})

# To install the font library required for specific fonts
!wget -q -O /content/TimesNewRoman.ttf https://github.com/justrajdeep/fonts/raw/master/Times%20New%20Roman.ttf
!wget -q -O /content/times.ttf https://github.com/FSKiller/Microsoft-Fonts/raw/main/times.ttf
!wget -q -O /content/timesbd.ttf https://github.com/FSKiller/Microsoft-Fonts/raw/main/timesbd.ttf

import matplotlib.font_manager as fm

fm.fontManager.addfont('/content/TimesNewRoman.ttf')
fm.fontManager.addfont('/content/times.ttf')
fm.fontManager.addfont('/content/timesbd.ttf')

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman']

plt.rcParams['font.weight'] = 'bold'
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titleweight'] = 'bold'

# To plot Decision Boundary

def plot_decision_boundary(df, local_w, local_b, update_num):
    n_features = len(local_w)
    if n_features == 1:
        plt.figure(figsize=(4, 1.5))
        for index, row in df.iterrows():
            x1, target = row[0], row[-1]
            color = 'blue' if target == 1 else 'red'
            plt.scatter(x1, 0, c=color, s=100, edgecolors='k', zorder=3)

        if local_w[0] != 0:
            x_boundary = -local_b / local_w[0]
            plt.axvline(x_boundary, color='g', label='Decision boundary')
        plt.xlim(-0.5, 1.5)
        plt.yticks([])
        plt.xlabel('x1')

    elif n_features == 2:
        plt.figure(figsize=(4, 4))
        for index, row in df.iterrows():
            x1, x2, target = row[0], row[1], row[-1]
            color = 'blue' if target == 1 else 'red'
            plt.scatter(x1, x2, c=color, s=100, edgecolors='k', zorder=3)

        x_vals = np.array([-0.5, 1.5])
        if local_w[1] != 0:
            y_vals = -(local_w[0] * x_vals + local_b) / local_w[1]
            plt.plot(x_vals, y_vals, 'g-', label='Decision boundary')
        elif local_w[0] != 0:
            x_line = -local_b / local_w[0]
            plt.axvline(x_line, color='g', label='Decision boundary')
        plt.xlim(-0.5, 1.5)
        plt.ylim(-0.5, 1.5)
        plt.xlabel('x1')
        plt.ylabel('x2')

    else:
        print(f"Plotting only supported for 1 or 2 features (got {n_features})")
        return

    plt.title(f"Decision boundary")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

# Training for AND gate

w=np.zeros(2)
b=0
print("Initial weights: ", w)
print("Initial bias: ", b)
print()
def AndPerceptron(df, lr, epochs):
  local_w = np.array([w[0], w[1]])
  local_b = b

  for i in range(epochs):
    for index, row in df.iterrows():
      features_for_dot = row[:-1].values
      target = row[-1]

      weighted_sum = np.dot(features_for_dot, local_w) + local_b

      if weighted_sum >= 0:
        prediction = 1
      else:
        prediction = 0

      error = target - prediction
      if error != 0:
        local_w += lr * error * features_for_dot

        local_b += lr * error

        print("Updated weight:",local_w)
        print("Updated bias:",local_b)
        print()
        plot_decision_boundary(df, local_w, local_b, i+1)


  return np.array([local_b, local_w[0], local_w[1]])

lr = 0.1
epochs = 100

trained_weights_and = AndPerceptron(AND_df, lr, epochs)

print(f"Trained weights for AND gate: {trained_weights_and}")


def predict(x1, x2, weights_array):
  features = np.array([1, x1, x2])
  weighted_sum = np.dot(features, weights_array)
  return 1 if weighted_sum >= 0 else 0

print("\nTesting AND gate predictions:")
a=int(input("Enter x1: "))
b=int(input("Enter x2: "))
print("Prediction:",predict(a, b, trained_weights_and))

w=np.zeros(2)
b=0

print("Initial weights: ", w)
print("Initial bias: ", b)
print()

def OrPerceptron(df, lr, epochs):
  local_w = np.array([w[0], w[1]])
  local_b = b

  for i in range(epochs):
    for index, row in df.iterrows():
      features_for_dot = row[:-1].values
      target = row[-1]

      weighted_sum = np.dot(features_for_dot, local_w) + local_b

      if weighted_sum >= 0:
        prediction = 1
      else:
        prediction = 0

      error = target - prediction
      if error != 0:
        local_w += lr * error * features_for_dot

        local_b += lr * error

        print("Updated weight:",local_w)
        print("Updated bias:",local_b)
        print()
        plot_decision_boundary(df, local_w, local_b, i+1)

  return np.array([local_b, local_w[0], local_w[1]])

lr = 0.1
epochs = 100

trained_weights_or = OrPerceptron(OR_df, lr, epochs)

print(f"Trained weights for OR gate: {trained_weights_or}")


print("\nTesting OR gate predictions:")
a=int(input("Enter x1: "))
b=int(input("Enter x2: "))

print("Prediction:",predict(a, b, trained_weights_or))

w = 0
b = 0
print("Initial weights: ", w)
print("Initial bias: ", b)
print()
def NotPerceptron(df, lr, epochs):
  local_w = w
  local_b = b

  for i in range(epochs):
    for index, row in df.iterrows():
      features = row[0]
      target = row[-1]

      weighted_sum = features * local_w + local_b

      if weighted_sum >= 0:
        prediction = 1
      else:
        prediction = 0

      error = target - prediction
      if error != 0:
        local_w += lr * error * features
        local_b += lr * error

        print("Updated weight:", local_w)
        print("Updated bias:", local_b)
        print()
        plot_decision_boundary(df, [local_w], local_b,i+1)

  return [local_b, local_w]
  return [local_b, local_w]

lr=0.1
epochs=100

def PredictNot(x1, weights_array):
  features = np.array([1, x1])
  weighted_sum = np.dot(features, weights_array)
  return 1 if weighted_sum >= 0 else 0

Not_trained_weights = NotPerceptron(NOT_df, lr, epochs)

print(f"Trained weights for NOT gate: {Not_trained_weights}")

print("\nTesting NOT gate predictions:")
a=int(input("Enter x1: "))
print("Prediction:",PredictNot(a, Not_trained_weights))